-- Run this script in your Supabase SQL Editor to create the necessary tables

-- Users table
CREATE TABLE public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);

-- Moods table
CREATE TABLE public.moods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    emotion TEXT NOT NULL,
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- Interactions table
CREATE TABLE public.interactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    song_id TEXT NOT NULL,
    song_title TEXT NOT NULL,
    action TEXT NOT NULL,
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- Note: In a production app you may want to enable Row Level Security (RLS)
-- and configure policies, but for this direct migration from SQLite it is 
-- sufficient to just create the tables.
